apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
spec:
  podFailurePolicy:
    rules:
      - action: FailJob
        onExitCodes:
          containerName: k6
          operator: In
          values: [99]
      - action: Ignore
        onPodConditions:
          - type: DisruptionTarget
  template:
    spec:
      serviceAccountName: load-test
      containers:
        - image: grafana/k6:0.48.0
          resources: {}
          name: k6
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 12345
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          command:
            - k6
          args:
            - run
            - /script/script.js
            - --no-usage-report
          env:
            - name: KUBERNETES_TOKEN
              valueFrom:
                secretKeyRef:
                  name: load-test-token
                  key: token
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # this is needed for custom or private CA's
            # there is no support for custom CA certs: https://github.com/grafana/k6/issues/218
            - name: K6_INSECURE_SKIP_TLS_VERIFY
              value: "true"
            - name: K6_VUS
              valueFrom:
                configMapKeyRef:
                  name: load-test
                  key: vus
            - name: K6_ITERATIONS
              valueFrom:
                configMapKeyRef:
                  name: load-test
                  key: iterations
          volumeMounts:
            - name: script
              mountPath: /script
      volumes:
        - name: script
          configMap:
            name: load-test
            items:
              - key: util.js
                path: util.js
              - key: script.js
                path: script.js
      restartPolicy: Never
