apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: load-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: load-test
  namespace: load-test
---
apiVersion: v1
kind: Secret
metadata:
  name: load-test-token
  annotations:
      kubernetes.io/service-account.name: load-test
type: kubernetes.io/service-account-token
